main.name = "pwnagotchi"
main.lang = "en"
main.whitelist = [
 "Hide Yo Kids, Hide Yo Wifi",
 "XX:XX:XX:XX:XX:XX",
]
main.plugins.bt-tether.enabled = true
main.plugins.bt-tether.phone-name = "Joe's S25"
main.plugins.bt-tether.phone = "android"
main.plugins.bt-tether.mac = "XX:XX:XX:XX:XX:XX"
main.plugins.bt-tether.ip = "192.168.44.44"

main.plugins.auto-tune.enabled = true
main.plugins.auto-tune.show_hidden = false
main.plugins.auto-tune.reset_history = true
main.plugins.auto-tune.extra_channels = 15

main.plugins.auto-update.enabled = true
main.plugins.auto-update.install = true
main.plugins.auto-update.interval = 1

main.plugins.fix_services.enabled = true

main.plugins.gdrivesync.enabled = false
main.plugins.gdrivesync.backupfiles = [ "",]
main.plugins.gdrivesync.backup_folder = "PwnagotchiBackups"

main.plugins.gpio_buttons.enabled = false

main.plugins.gps.enabled = false
main.plugins.gps.speed = 19200
main.plugins.gps.device = "/dev/ttyUSB0"

main.plugins.gps_listener.enabled = false

main.plugins.grid.enabled = true
main.plugins.grid.report = true

main.plugins.logtail.enabled = true
main.plugins.logtail.max-lines = 10000

main.plugins.memtemp.enabled = true
main.plugins.memtemp.scale = "celsius"
main.plugins.memtemp.orientation = "horizontal"

main.plugins.ohcapi.enabled = false
main.plugins.ohcapi.api_key = "sk_your_api_key_here"
main.plugins.ohcapi.receive_email = "yes"

main.plugins.pwndroid.enabled = true
main.plugins.pwndroid.display = false
main.plugins.pwndroid.display_altitude = false

main.plugins.pisugarx.enabled = false
main.plugins.pisugarx.rotation = false
main.plugins.pisugarx.default_display = "percentage"

main.plugins.session-stats.enabled = false
main.plugins.session-stats.save_directory = "/var/tmp/pwnagotchi/sessions/"

main.plugins.ups_hat_c.enabled = false
main.plugins.ups_hat_c.label_on = true
main.plugins.ups_hat_c.shutdown = 5
main.plugins.ups_hat_c.bat_x_coord = 140
main.plugins.ups_hat_c.bat_y_coord = 0

main.plugins.ups_lite.enabled = false
main.plugins.ups_lite.shutdown = 2

main.plugins.webcfg.enabled = true
main.plugins.webgpsmap.enabled = false

main.plugins.wigle.enabled = false
main.plugins.wigle.api_key = ""
main.plugins.wigle.donate = false

main.plugins.wpa-sec.enabled = true
main.plugins.wpa-sec.api_key = ""
main.plugins.wpa-sec.api_url = "https://wpa-sec.stanev.org"
main.plugins.wpa-sec.download_results = false
main.plugins.wpa-sec.show_pwd = false

main.plugins.aircrackonly.enabled = true
main.plugins.aircrackonly.face = "(>.<)"

main.plugins.display-password.enabled = true
main.plugins.handshakes-dl.enabled = true
main.plugins.hashie.enabled = true
main.plugins.instattack.enabled = true

main.plugins.quickdic.enabled = true
main.plugins.quickdic.face = "(·ω·)"

main.plugins.uncracked.enabled = true
main.plugins.probenpwn.enabled = false
main.plugins.screen_refresh.enabled = false
main.plugins.exp.enabled = false
main.plugins.enable_assoc.enabled = false

main.plugins.led.enabled = true
main.plugins.away_base.enabled = false
main.plugins.better_quickdic.enabled = true
main.plugins.bluetoothsniffer.enabled = false
main.plugins.counter.enabled = false
main.plugins.display-password-qr.enabled = true
main.plugins.hashie-hcxpcapngtool.enabled = true

main.plugins.home_base.enabled = false
main.plugins.home_base.networks.YOUR_HOME_SSID.password = "wifi_password"
main.plugins.home_base.networks.YOUR_HOME_SSID.identity = "wifi_name"

main.plugins.hashieclean.enabled = true
main.plugins.IPDisplay.enabled = false
main.plugins.IPDisplay.skip_devices = [ "lo",]
main.plugins.enable_deauth.enabled = false
main.plugins.snoopr.enabled = true

main.confd = "/etc/pwnagotchi/conf.d/"
main.custom_plugins = "/usr/local/share/pwnagotchi/custom-plugins/"
main.custom_plugin_repos = [
 "https://github.com/jayofelony/pwnagotchi-torch-plugins/archive/master.zip",
 "https://github.com/evilsocket/pwnagotchi-plugins-contrib/archive/master.zip",
 "https://github.com/Sniffleupagus/pwnagotchi_plugins/archive/master.zip",
 "https://github.com/NeonLightning/pwny/archive/master.zip",
 "https://github.com/marbasec/UPSLite_Plugin_1_3/archive/master.zip",
 "https://github.com/wpa-2/Pwnagotchi-Plugins/archive/master.zip",
 "https://github.com/cyberartemio/wardriver-pwnagotchi-plugin/archive/main.zip",
 "https://github.com/AlienMajik/pwnagotchi_plugins/archive/refs/heads/main.zip",
 "https://github.com/avipars/pwnagotchi-plugins/archive/master.zip",
]
main.iface = "wlan0mon"
main.mon_start_cmd = "/usr/bin/monstart"
main.mon_stop_cmd = "/usr/bin/monstop"
main.mon_max_blind_epochs = 5
main.no_restart = false
main.log.path = "/etc/pwnagotchi/log/pwnagotchi.log"
main.log.path-debug = "/etc/pwnagotchi/log/pwnagotchi-debug.log"
main.log.rotation.enabled = true
main.log.rotation.size = "10M"

main.ai.enabled = true
main.ai.path = "/root/brain.nn"
main.ai.laziness = 0.1

main.plugin.gdrivesync.interval = 1

ui.display.enabled = true
ui.display.type = "waveshare_3"
ui.display.color = "black"
ui.display.rotation = 180

ui.fps = 1.0
ui.invert = true
ui.cursor = true
ui.font.name = "DejaVuSansMono"
ui.font.size_offset = 0

ui.faces.look_r = "( ⚆_⚆)"
ui.faces.look_l = "(☉_☉ )"
ui.faces.look_r_happy = "( ◕‿◕)"
ui.faces.look_l_happy = "(◕‿◕ )"
ui.faces.sleep = "(⇀‿‿↼)"
ui.faces.sleep2 = "(≖‿‿≖)"
ui.faces.awake = "(◕‿‿◕)"
ui.faces.bored = "(-__-)"
ui.faces.intense = "(°▃▃°)"
ui.faces.cool = "(⌐■_■)"
ui.faces.happy = "(•‿‿•)"
ui.faces.excited = "(ᵔ◡◡ᵔ)"
ui.faces.grateful = "(^‿‿^)"
ui.faces.motivated = "(☼‿‿☼)"
ui.faces.demotivated = "(≖__≖)"
ui.faces.smart = "(✜‿‿✜)"
ui.faces.lonely = "(ب__ب)"
ui.faces.sad = "(╥☁╥ )"
ui.faces.angry = "(-_-')"
ui.faces.friend = "(♥‿‿♥)"
ui.faces.broken = "(☓‿‿☓)"
ui.faces.debug = "(#__#)"
ui.faces.upload = "(1__0)"
ui.faces.upload1 = "(1__1)"
ui.faces.upload2 = "(0__1)"

ui.web.enabled = true
ui.web.address = "::"
ui.web.auth = false
ui.web.username = "pwnagotchi"
ui.web.password = "pwnagotchi"
ui.web.origin = ""
ui.web.port = 8080
ui.web.on_frame = ""

bettercap.username = "pwnagotchi"
bettercap.password = "pwnagotchi"
bettercap.handshakes = "/home/pi/handshakes"
bettercap.silence = [
 "ble.device.new",
 "ble.device.lost",
 "ble.device.disconnected",
 "ble.device.connected",
 "ble.device.service.discovered",
 "ble.device.characteristic.discovered",
 "wifi.client.new",
 "wifi.client.lost",
 "wifi.client.probe",
 "wifi.ap.new",
 "wifi.ap.lost",
 "mod.started",
]

personality.advertise = true
personality.deauth = true
personality.associate = true
personality.channels = [
 3,
 9,
 2,
 8,
 6,
 1,
 5,
 7,
 10,
 4,
 11,
]
personality.min_rssi = -85.0
personality.ap_ttl = 300.0
personality.sta_ttl = 300.0
personality.recon_time = 30.0
personality.max_inactive_scale = 2
personality.recon_inactive_multiplier = 2
personality.hop_recon_time = 10
personality.min_recon_time = 5
personality.max_interactions = 3
personality.max_misses_for_recon = 5
personality.excited_num_epochs = 10
personality.bored_num_epochs = 15
personality.sad_num_epochs = 25
personality.bond_encounters_factor = 20000
personality.throttle_a = 0.2
personality.throttle_d = 0.2

fs.memory.enabled = true
fs.memory.mounts.log.enabled = true
fs.memory.mounts.log.mount = "/etc/pwnagotchi/log/"
fs.memory.mounts.log.size = "50M"
fs.memory.mounts.log.sync = 60
fs.memory.mounts.log.zram = true
fs.memory.mounts.log.rsync = true

fs.memory.mounts.data.enabled = true
fs.memory.mounts.data.mount = "/var/tmp/pwnagotchi"
fs.memory.mounts.data.size = "10M"
fs.memory.mounts.data.sync = 3600
fs.memory.mounts.data.zram = true
fs.memory.mounts.data.rsync = true

ai.params.gamma = 0.99
ai.params.n_steps = 1
ai.params.vf_coef = 0.25
ai.params.ent_coef = 0.01
ai.params.max_grad_norm = 0.5
ai.params.learning_rate = 0.001
ai.params.alpha = 0.99
ai.params.epsilon = 1e-5
ai.params.verbose = 1
ai.params.lr_schedule = "constant"


